version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zk_eq
    container_name: zk_eq
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka_eq
    container_name: kafka_eq
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zk_eq:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "earthquake:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  scraper:
    #image: cemayan/earthquake-scraper-mini:1.0
    image: ./scraper
    ports:
      - "8085:8085"
